name: Playwright Tests
on:
 push:
  branches: [main, master]
 pull_request:
  branches: [main, master]
jobs:
 test:
  timeout-minutes: 60
  runs-on: ubuntu-latest

phases:
 install:
  commands:
   - npm ci
   - npx playwright install
   - npx playwright install-deps
 build:
  commands:
   - npx playwright test --config=playwright.config.ts --project=Webkit
   - npx playwright test --config=playwright.config.ts --project=Chromium
   - npx playwright test --config=playwright.config.ts --project=Firefox
artifacts:
 files:
  - '*.png'
  - 'test-results/**/*'
  - 'playwright-report/**/*'
